In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from scipy.spatial.transform import Rotation as r

# Test the Rotation Scipy's module

In [4]:
# define a rotation using Euler angles (Bunge convention)
rotation = r.from_euler('zxz', [30, 45, 40], degrees=True)

In [20]:
print(f"Euler angles: {rotation.as_euler('zxz', degrees=True)} (Bunge convention)")
print(f"Euler angles: {rotation.as_euler('zxy', degrees=True)} (Other)")
print(f"Quaternions: {rotation.as_quat()}")
print(f"Rotation vectors: {rotation.as_rotvec(degrees=True)}")
print(f"Modified Rodrigues Parameters: {rotation.as_mrp()}")
print(f"Rotation matrix: \n {rotation.as_matrix()}")

Euler angles: [30. 45. 40.] (Bunge convention)
Euler angles: [79.87925979 32.79775133 32.73240721] (Other)
Quaternions: [0.38122721 0.03335306 0.52991553 0.75679781]
Rotation vectors: [47.61167346  4.16548168 66.18143918]
Modified Rodrigues Parameters: [0.21700119 0.01898514 0.30163718]
Rotation matrix: 
 [[ 0.43615421 -0.77664764  0.45451948]
 [ 0.82750801  0.1477107  -0.54167522]
 [ 0.35355339  0.61237244  0.70710678]]


## Apply this rotation to a set of vectors.

## Get the magnitude(s) of the rotation(s)

## Get identity rotation(s)

## Reduce this rotation with the provided rotation groups

In [23]:
rotation.magnitude()

1.424792303615968

In [25]:
np.rad2deg(rotation.magnitude())

81.63458567991715

In [26]:
rotation.identity()